/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationAutomatID_OTML_h
#define ProjectConfigurationAutomatID_OTML_h

	#define SKIP_DEBUG_AND_JAILBREAK_SECURITY_CHECK
	#undef CERTIFICATE_PINNING_DISABLED
	#define ANTI_SCREEN_RECORDING_DISABLED
	#undef LAYOUT_DEBUG_ENABLED
	#undef ACCESSIBILITY_IDENTIFIERS_ENABLED
	#define EXCLUDE_COCOA_CNCONTACTS
	#define EXCLUDE_COCOA_CORE_LOCATION
	#define EXLUDE_COCOA_PUSH_NOTIFICATIONS

#endif /* ProjectConfigurationAutomatID_OTML_h*/