/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationOTMLFaceRecognitionAddon_h
#define ProjectConfigurationOTMLFaceRecognitionAddon_h

	#undef OTML_FACE_RECOGNITION_DEBUG_ENABLED

#endif /* ProjectConfigurationOTMLFaceRecognitionAddon_h*/