/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationAutomatID_OTMLFaceRecognitionAddon_h
#define ProjectConfigurationAutomatID_OTMLFaceRecognitionAddon_h

	#undef OTML_FACE_RECOGNITION_DEBUG_ENABLED

#endif /* ProjectConfigurationAutomatID_OTMLFaceRecognitionAddon_h*/