/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationAutomatID_OTMLCore_h
#define ProjectConfigurationAutomatID_OTMLCore_h

	#define LOGACTIVE
	#undef COREMULTIPUNTAMENTO
	#define LOG_DESTINATION AutomatID_OTMPLoggerProcessor_NSLog

#endif /* ProjectConfigurationAutomatID_OTMLCore_h*/