/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationOTHFOTMLFaceRecognitionAddon_h
#define ProjectConfigurationOTHFOTMLFaceRecognitionAddon_h

	#undef OTML_FACE_RECOGNITION_DEBUG_ENABLED

#endif /* ProjectConfigurationOTHFOTMLFaceRecognitionAddon_h*/