extern NSString* const c_AutomatID_OTMLVideoPlayerConstants_action_command_video_player;

extern NSString* const c_AutomatID_OTMLVideoPlayerConstants_action_command_video_player_param_url;

extern NSString* const c_AutomatID_OTMLVideoPlayerConstants_action_command_video_player_param_auto_reach;

extern NSString* const c_AutomatID_OTMLVideoPlayerConstants_trigger_otml_video_player_dismiss;

extern NSString* const c_AutomatID_OTMLVideoPlayerConstants_trigger_otml_video_player_fail;



@interface AutomatID_OTMLVideoPlayerConstants : NSObject
@end