extern NSString* const c_OTMLParameterConstants_device_parameter_srcid_device;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_sim_id;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_imei;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_platform;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_sub_platform;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_cluster;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_tablet;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_orientation;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_orientation_value_portrait;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_orientation_value_landscape;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_user_agent;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_brand;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_model;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_hardware_model;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_os_version;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_uuid;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_device_id;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_display_short_side_pixel;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_display_long_side_pixel;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_main_window_width;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_main_window_height;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_context_width_;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_context_height_;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_natural_width;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_natural_height;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_width;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_height;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_logical_width;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_screen_logical_height;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_generateuuid;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_bluetooth_on;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_has_connection;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_intact;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_intact_value_unknown;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_main_window_width_px;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_main_window_height_px;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_nfc_on;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_device_protected;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_device_protection_method;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_device_protection_method_value_pin_or_password;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_device_protection_method_value_none;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_device_protection_method_value_unknown;

extern NSString* const c_OTMLParameterConstants_device_parameter_flagforsrc_is_small_device;

extern NSString* const c_OTMLParameterConstants_mapname_parameter_srcid_map_name;

extern NSString* const c_OTMLParameterConstants_entry_parameter_srcid_entry;

extern NSString* const c_OTMLParameterConstants_entry_parameter_flagforsrc_contextid;

extern NSString* const c_OTMLParameterConstants_datetime_parameter_srcid_date_time;

extern NSString* const c_OTMLParameterConstants_datetime_parameter_flagforsrc_device_daylightsaving_time;

extern NSString* const c_OTMLParameterConstants_datetime_parameter_flagforsrc_current_timestamp;

extern NSString* const c_OTMLParameterConstants_datetime_parameter_flagforsrc_device_timezone;

extern NSString* const c_OTMLParameterConstants_datetime_parameter_flagforsrc_current_timestamp_with_server_offset;

extern NSString* const c_OTMLParameterConstants_locale_parameter_srcid_locale;

extern NSString* const c_OTMLParameterConstants_locale_parameter_flagforsrc_app_locale;

extern NSString* const c_OTMLParameterConstants_locale_parameter_flagforsrc_device_locale;

extern NSString* const c_OTMLParameterConstants_camera_parameter_srcid_camera;

extern NSString* const c_OTMLParameterConstants_camera_parameter_flagforsrc_has_torch;

extern NSString* const c_OTMLParameterConstants_camera_parameter_flagforsrc_torch_n;

extern NSString* const c_OTMLParameterConstants_parameter_srcid_prefix;



@interface OTMLParameterConstants : NSObject
@end