/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationOTHFOTMLCore_h
#define ProjectConfigurationOTHFOTMLCore_h

	#undef LOGACTIVE
	#undef COREMULTIPUNTAMENTO
	#define LOG_DESTINATION AutomatID_OTMPLoggerProcessor_NSLog

#endif /* ProjectConfigurationOTHFOTMLCore_h*/