extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_srcid;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_flagforsrc_has_nfc;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_flagforsrc_is_nfc_on;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_action_open_nfc_settings;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_action_nfc_document_read;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_read_progress_full;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_read_progress_empty;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_request_present_passport;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_connecting_to_passport;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_authenticating_with_passport;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_reading_datagroup_progress;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_successful_read_msg;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_tag_non_valid_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_more_than_one_tag_found_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_connection_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_invalid_mrz_key_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_response_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_nfc_default_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_popup_bg_color;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_title_text;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_title_fontstyle;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_anim_waiting;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_anim_success;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_anim_error;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_status_text_fontstyle;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_progressbar_bg_color;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_progressbar_fg_color;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_btn_cancel_text;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_btn_cancel_fontstyle;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_cancel_btn_bg_color_n;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_and_cancel_btn_bg_color_d;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_read_started_event;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_success_event;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_error_event;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_cancel_event;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_document_number;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_expiration_date;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_birth_date;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_start_event_default_value;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_success_event_default_value;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_error_event_default_value;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_cancel_event_default_value;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_nfc_document_read_param_read_photo_record;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_dg1;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_dg2;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_sod;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_picture;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_mrz_key;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_document_type;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_document_number;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_issuing_country;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_nationality;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_surname;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_name;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_splitted_surname;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_splitted_name;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_date_of_birth;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_date_of_birth_year;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_date_of_birth_month;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_date_of_birth_day;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_sex;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_expiration_date;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_expiration_date_year;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_expiration_date_month;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_mrz_expiration_date_day;

extern NSString* const c_AutomatID_OTML_NFCdocumentReaderConstants_ds_field_ca_succeeded;



@interface AutomatID_OTML_NFCdocumentReaderConstants : NSObject
@end