/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationOTMLCore_h
#define ProjectConfigurationOTMLCore_h

	#undef LOGACTIVE
	#undef COREMULTIPUNTAMENTO
	#define LOG_DESTINATION OTMPLoggerProcessor_NSLog

#endif /* ProjectConfigurationOTMLCore_h*/