extern NSString* const c_AutomatID_OTMLFirebaseCommandConstants_cmd_log_event;

extern NSString* const c_AutomatID_OTMLFirebaseCommandConstants_param_suffix_double;

extern NSString* const c_AutomatID_OTMLFirebaseCommandConstants_param_suffix_long;

extern NSString* const c_AutomatID_OTMLFirebaseCommandConstants_param_event_name;



@interface AutomatID_OTMLFirebaseCommandConstants : NSObject
@end