extern NSString* const c_AutomatID_OTMLDatasourceActionConstants_datasource_crud_ds_save_trigger_ko;

extern NSString* const c_AutomatID_OTMLDatasourceActionConstants_datasource_crud_ds_save_trigger_ok;

extern NSString* const c_AutomatID_OTMLDatasourceActionConstants_ds_reset_trigger_ok;

extern NSString* const c_AutomatID_OTMLDatasourceActionConstants_ds_reset_trigger_ko;



@interface AutomatID_OTMLDatasourceActionConstants : NSObject
@end