extern NSString* const c_AutomatID_OTMLImageAttributeConstants_base_64_image_content_key;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_storage_mem;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_storage_file;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_mod_multiply_key;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_mod_rotation_key;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_mod_mirror_key;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_mod_padding_key;

extern NSString* const c_AutomatID_OTMLImageAttributeConstants_mod_cap_key;



@interface AutomatID_OTMLImageAttributeConstants : NSObject
@end